### ISSUE TITLE
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

### ISSUE THREAD

**Issue by mpalourdio** [DSI-VD/foehn#745]
## Description
This warning is shown in chromium 72 and firefox 65 (foehn 1.0.6). Could be cool to get rid of it. 
Not tested on IE, because I just don't care :)

**Comment by alienlebarge** [comment]
I've createt an issue on our side about that ([FOEHN-65](https://www.portail.vd.ch/outils/jira/secure/RapidBoard.jspa?rapidView=491&view=planning&selectedIssue=FOEHN-65))
thanks
